### ISSUE TITLE
when excute the run_testing.py ,i have a problem,it said ========  Evaluate the results ======================= Calculating results only inside the FOV: y scores pixels: 2429685 (radius 270: 270*270*3.14==228906), including background around retina: 6599200 (584*565==329960) y true pixels: 2429685 (radius 270: 270*270*3.14==228906), including background around retina: 6599200 (584*565==329960) Traceback (most recent call last):   File "./src/retinaNN_predict.py", line 183, in <module>     precision, recall, thresholds = precision_recall_curve(y_true, y_scores)   File "/home/liushixin/anaconda3/lib/python3.6/site-packages/sklearn/metrics/ranking.py", line 441, in precision_recall_curve     sample_weight=sample_weight)   File "/home/liushixin/anaconda3/lib/python3.6/site-packages/sklearn/metrics/ranking.py", line 318, in _binary_clf_curve     raise ValueError("{0} format is not supported".format(y_type)) ValueError: continuous format is not supported

### ISSUE THREAD

**Issue by ruda0214** [orobix/retina-unet#57]
========  Evaluate the results =======================
Calculating results only inside the FOV:
y scores pixels: 2429685 (radius 270: 270*270*3.14==228906), including background around retina: 6599200 (584*565==329960)
y true pixels: 2429685 (radius 270: 270*270*3.14==228906), including background around retina: 6599200 (584*565==329960)
Traceback (most recent call last):
  File "./src/retinaNN_predict.py", line 183, in <module>
    precision, recall, thresholds = precision_recall_curve(y_true, y_scores)
  File "/home/liushixin/anaconda3/lib/python3.6/site-packages/sklearn/metrics/ranking.py", line 441, in precision_recall_curve
    sample_weight=sample_weight)
  File "/home/liushixin/anaconda3/lib/python3.6/site-packages/sklearn/metrics/ranking.py", line 318, in _binary_clf_curve
    raise ValueError("{0} format is not supported".format(y_type))
ValueError: continuous format is not supported
anyone can give some advice?

**Comment by ruda0214** [comment]
@lantiga @dcorti do you meet this isue before? i have google it ,but nothing to flound.

**Comment by ruda0214** [comment]
i have solved this questions, i got a mistake in file 'prepare_dataset.py',and the parameter Nimgs should be the same with the total training number of your data.
