### ISSUE TITLE
errors in Windows+tensorflow_GPU environment

### ISSUE THREAD

**Issue by IronLavender** [orobix/retina-unet#67]
Hello, Your experiment is Ubuntu？my expereimen is Windows+tensorflow_GPU, but it occurs error when I run the retinaNN_training.py：
`Traceback (most recent call last):
  File "D:/Study/CODES/Medical_Segmentation/Keras_retina-unet/src/retinaNN_training.py", line 145, in <module>
    path_data = config.get('data paths', 'path_local')  # 数据文件封装后的文件路径
  File "E:\Learning\Anaconda3\envs\tensorflow_gpu\lib\configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "E:\Learning\Anaconda3\envs\tensorflow_gpu\lib\configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'data paths'`
but in configurations.txt, I think it's right :
`[data paths]
path_local =  ./DRIVE_datasets_training_testing/
train_imgs_original = DRIVE_dataset_imgs_train.hdf5
train_groundTruth = DRIVE_dataset_groundTruth_train.hdf5
train_border_masks = DRIVE_dataset_borderMasks_train.hdf5
test_imgs_original = DRIVE_dataset_imgs_test.hdf5
test_groundTruth = DRIVE_dataset_groundTruth_test.hdf5
test_border_masks = DRIVE_dataset_borderMasks_test.hdf5
`
I fail to correct it, so this does not work in a window environment?
Thank you for your work!

**Comment by NeoKun004** [comment]
it does work in windows environment but there is a config file needs to be created and located to force the training to run on theano backenend, here is my email I would love to help u through this 
my email: ahmed.beji004@gmail.com

**Comment by boba1234** [comment]
Hi, i am having this NosectionError: No section: 'data paths' too. Is there any solution to it? Thanks!

**Comment by Hridoy-bit** [comment]
Hi, I have got the same error . configparser.NoSectionError: No section: 'data paths'. 
 Any solution?I emailed you NeoKun004.
